version: "3.8"  # Используем актуальную версию

services:

    db:
        image: postgres:latest
            restart: always
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    app:
        build:
            context: .
            dockerfile: Dockerfile.production
        image: user99430e/fastify-app:latest
        ports:
           - "3000:8080"
        environment:
              DATABASE_HOST: ${DATABASE_HOST}
              DATABASE_NAME: ${DATABASE_NAME}
              DATABASE_USERNAME: ${DATABASE_USERNAME}
              DATABASE_PASSWORD: ${DATABASE_PASSWORD}
              DATABASE_PORT: ${DATABASE_PORT}
            depends_on:
              - db
        command: bash -c 'sleep 3 && npm test'
        restart: unless-stopped  # Автоперезапуск при падении
