version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash -c 'sleep 3 && npm start'"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile